# Generated by Django 5.2.5 on 2025-09-02 01:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albergues', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Nombre de usuario')),
                ('first_name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=150, verbose_name='Apellido')),
                ('is_active', models.BooleanField(default=True, verbose_name='Usuario activo')),
                ('is_staff', models.BooleanField(default=True, verbose_name='Es staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Es superusuario')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Actualizado en')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Último acceso')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('main_hostel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='albergues.hostel', verbose_name='Albergue principal')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'ordering': ['-last_login', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=150, verbose_name='Apellido')),
                ('phone_number', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en formato: '+999999999'. Máximo 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Número de teléfono')),
                ('age', models.PositiveIntegerField(verbose_name='Edad')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Género')),
                ('poverty_level', models.CharField(choices=[('LEVEL_1', 'Nivel 1'), ('LEVEL_2', 'Nivel 2'), ('LEVEL_3', 'Nivel 3')], default='LEVEL_1', max_length=20, verbose_name='Nivel de pobreza')),
                ('is_active', models.BooleanField(default=True, verbose_name='Usuario activo')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprobado en')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_users_approved', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number'], name='users_custo_phone_n_f2d675_idx'), models.Index(fields=['is_active'], name='users_custo_is_acti_1b62ea_idx')],
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en formato: '+999999999'. Máximo 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Número de teléfono')),
                ('hashed_code', models.CharField(max_length=255, verbose_name='Código hasheado')),
                ('is_used', models.BooleanField(default=False, verbose_name='Código usado')),
                ('expires_at', models.DateTimeField(verbose_name='Expira en')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Intentos')),
                ('max_attempts', models.PositiveIntegerField(default=3, verbose_name='Máximo de intentos')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Código OTP',
                'verbose_name_plural': 'Códigos OTP',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number'], name='users_otpco_phone_n_c7ea1e_idx'), models.Index(fields=['expires_at'], name='users_otpco_expires_10477f_idx')],
            },
        ),
        migrations.CreateModel(
            name='PreRegisterUser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=150, verbose_name='Apellido')),
                ('phone_number', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en formato: '+999999999'. Máximo 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Número de teléfono')),
                ('age', models.PositiveIntegerField(verbose_name='Edad')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Género')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('privacy_policy_accepted', models.BooleanField(default=False, verbose_name='Política de privacidad aceptada')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Pre-registro de Usuario',
                'verbose_name_plural': 'Pre-registros de Usuarios',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number'], name='users_prere_phone_n_6df58e_idx'), models.Index(fields=['status'], name='users_prere_status_707569_idx')],
            },
        ),
    ]
