# Generated by Django 5.2.5 on 2025-09-11 00:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_otpcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en formato internacional con código de país: '+521234567890'. Ejemplo: +52811908593", regex='^\\+\\d{10,15}$')], verbose_name='Número de teléfono'),
        ),
        migrations.AlterField(
            model_name='preregisteruser',
            name='phone_number',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en formato internacional con código de país: '+521234567890'. Ejemplo: +52811908593", regex='^\\+\\d{10,15}$')], verbose_name='Número de teléfono'),
        ),
        migrations.CreateModel(
            name='CustomUserToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Clave del token')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='users.customuser', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Token de Usuario',
                'verbose_name_plural': 'Tokens de Usuarios',
            },
        ),
    ]
