# Generated by Django 5.2.5 on 2025-08-28 00:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostelService',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Desactivado en')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Servicio de albergue',
                'verbose_name_plural': 'Servicios de albergue',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationService',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Desactivado en')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('rejected', 'Rechazada'), ('completed', 'Completada'), ('in_progress', 'En progreso')], max_length=255, verbose_name='Estado')),
                ('type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Grupo')], max_length=255, verbose_name='Tipo')),
                ('men_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad de hombres')),
                ('women_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad de mujeres')),
                ('datetime_reserved', models.DateTimeField(verbose_name='Fecha y hora de reserva')),
                ('end_datetime_reserved', models.DateTimeField(verbose_name='Fecha y hora de fin de reserva')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Desactivado en')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('reservation_type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Grupo')], max_length=255, verbose_name='Tipo de reserva')),
                ('needs_approval', models.BooleanField(default=False, verbose_name='Necesita aprobación')),
                ('max_time', models.PositiveIntegerField(help_text='Tiempo máximo de reserva en minutos', verbose_name='Tiempo máximo de reserva')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Desactivado en')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(verbose_name='Día de la semana')),
                ('start_time', models.TimeField(verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de fin')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
            ],
            options={
                'verbose_name': 'Horario de servicio',
                'verbose_name_plural': 'Horarios de servicio',
                'ordering': ['-created_at'],
            },
        ),
    ]
