# Generated by Django 5.2.5 on 2025-08-28 00:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Desactivado en')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre descriptivo del inventario (ej: Inventario Principal)', max_length=255, verbose_name='Nombre del inventario')),
                ('description', models.TextField(blank=True, help_text='Descripción del inventario', verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Desactivado en')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Cantidad disponible del artículo en este inventario', verbose_name='Cantidad')),
                ('minimum_stock', models.PositiveIntegerField(default=0, help_text='Cantidad mínima recomendada para mantener en stock', verbose_name='Stock mínimo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Artículo de inventario',
                'verbose_name_plural': 'Artículos de inventario',
                'ordering': ['item__category', 'item__name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Desactivado en')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del artículo')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del artículo', verbose_name='Descripción')),
                ('category', models.CharField(help_text='Categoría del artículo (ej: Higiene, Alimentos, Limpieza)', max_length=100, verbose_name='Categoría')),
                ('unit', models.CharField(help_text='Unidad de medida (ej: piezas, paquetes, kg, litros)', max_length=50, verbose_name='Unidad de medida')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['category', 'name'],
            },
        ),
    ]
