# Generated by Django 5.2.5 on 2025-08-28 00:44

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Desactivado en')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('phone', models.CharField(db_index=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="El número telefónico debe estar en formato: '+XX XXXXXXXXXX'.", regex='^\\+\\d{1,3}\\s\\d{7,15}$')], verbose_name='Número telefónico')),
                ('men_capacity', models.PositiveIntegerField(blank=True, help_text='Número máximo de hombres que puede albergar el albergue', null=True, verbose_name='Capacidad de hombres')),
                ('women_capacity', models.PositiveIntegerField(blank=True, help_text='Número máximo de mujeres que puede albergar el albergue', null=True, verbose_name='Capacidad de mujeres')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el albergue está activo', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Albergue',
                'verbose_name_plural': 'Albergues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HostelReservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Desactivado en')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('rejected', 'Rechazada'), ('completed', 'Completada')], max_length=255, verbose_name='Estado')),
                ('type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Grupo')], max_length=255, verbose_name='Tipo')),
                ('arrival_date', models.DateField(verbose_name='Fecha de llegada')),
                ('men_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad de hombres')),
                ('women_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad de mujeres')),
            ],
            options={
                'verbose_name': 'Reserva de albergue',
                'verbose_name_plural': 'Reservas de albergue',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Desactivado en')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Coordenada de latitud (ej: 19.4326)', max_digits=9, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Coordenada de longitud (ej: -99.1332)', max_digits=9, verbose_name='Longitud')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('city', models.CharField(max_length=255, verbose_name='Ciudad')),
                ('state', models.CharField(max_length=255, verbose_name='Estado')),
                ('country', models.CharField(default='México', max_length=100, verbose_name='País')),
                ('zip_code', models.CharField(max_length=20, verbose_name='Código postal')),
                ('timezone', models.CharField(default='America/Mexico_City', max_length=50, verbose_name='Zona horaria')),
                ('landmarks', models.TextField(blank=True, help_text='Descripción de puntos de referencia cercanos', verbose_name='Puntos de referencia')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
