# Generated by Django 5.2.5 on 2025-09-11 00:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albergues', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='phone',
            field=models.CharField(db_index=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en formato internacional con código de país: '+521234567890'. Ejemplo: +52811908593", regex='^\\+\\d{10,15}$')], verbose_name='Número telefónico'),
        ),
    ]
