# Generated by Django 5.2.5 on 2025-10-01 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albergues', '0003_alter_hostel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='current_men_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Número de hombres que actualmente alberga el albergue', null=True, verbose_name='Capacidad de hombres actual'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='current_women_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Número de mujeres que actualmente alberga el albergue', null=True, verbose_name='Capacidad de mujeres actual'),
        ),
    ]
