# Generated by Django 5.2.5 on 2025-10-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albergues', '0004_hostel_current_men_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelreservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('rejected', 'Rechazada'), ('checked_in', 'Check-in'), ('checked_out', 'Check-out')], max_length=255, verbose_name='Estado'),
        ),
    ]
