# Generated by Django 5.2.5 on 2025-10-15 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albergues', '0005_alter_hostelreservation_status'),
        ('users', '0003_alter_customuser_phone_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelreservation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='hostelreservation',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='hostelreservation',
            name='created_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_admin', to=settings.AUTH_USER_MODEL, verbose_name='Creado por (Admin)'),
        ),
        migrations.AddField(
            model_name='hostelreservation',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_user', to='users.customuser', verbose_name='Creado por (Usuario)'),
        ),
        migrations.AddField(
            model_name='hostelreservation',
            name='updated_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by_admin', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por (Admin)'),
        ),
        migrations.AddField(
            model_name='hostelreservation',
            name='updated_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by_user', to='users.customuser', verbose_name='Actualizado por (Usuario)'),
        ),
    ]
