# Generated by Django 5.2.5 on 2025-10-17 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albergues', '0006_remove_hostelreservation_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelreservation',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('rejected', 'Rechazada'), ('checked_in', 'Check-in'), ('checked_out', 'Check-out')], default='pending', max_length=255, null=True, verbose_name='Estado'),
        ),
    ]
