# Generated by Django 5.2.5 on 2025-10-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albergues', '0007_alter_hostelreservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL de la imagen del albergue', null=True, verbose_name='URL de la imagen del albergue'),
        ),
    ]
